# Generated by Django 5.2.8 on 2025-12-17 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVisit',
            fields=[
                ('visit_date', models.DateField(primary_key=True, serialize=False)),
                ('visit_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'daily_visit',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dep_id', models.AutoField(primary_key=True, serialize=False)),
                ('dep_name', models.CharField(max_length=255)),
                ('dep_code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='DimDisease',
            fields=[
                ('disease_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('disease_name', models.CharField(max_length=100)),
                ('icd_group_name', models.CharField(blank=True, max_length=50, null=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('ai_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dim_disease',
            },
        ),
        migrations.CreateModel(
            name='ErInfo',
            fields=[
                ('er_id', models.AutoField(primary_key=True, serialize=False)),
                ('hpid', models.CharField(max_length=20, unique=True)),
                ('er_name', models.CharField(max_length=100)),
                ('er_address', models.CharField(max_length=255)),
                ('er_sido', models.CharField(max_length=30)),
                ('er_sigungu', models.CharField(max_length=30)),
                ('er_lat', models.FloatField(blank=True, null=True)),
                ('er_lng', models.FloatField(blank=True, null=True)),
                ('place_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'er_info',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hos_id', models.AutoField(primary_key=True, serialize=False)),
                ('hpid', models.CharField(max_length=400, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hos_name', models.CharField(max_length=50)),
                ('hos_password', models.CharField(max_length=255)),
                ('tel', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('category_name', models.CharField(blank=True, max_length=150, null=True)),
                ('homepage', models.CharField(blank=True, max_length=255, null=True)),
                ('estb_date', models.CharField(blank=True, max_length=20, null=True)),
                ('sido', models.CharField(blank=True, max_length=6, null=True)),
                ('sggu', models.CharField(blank=True, max_length=6, null=True)),
                ('dr_total', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hospital',
            },
        ),
        migrations.CreateModel(
            name='LabData',
            fields=[
                ('lab_id', models.AutoField(primary_key=True, serialize=False)),
                ('lab_code', models.CharField(max_length=20)),
                ('lab_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'lab_data',
            },
        ),
        migrations.CreateModel(
            name='LabOrders',
            fields=[
                ('lab_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SAMPLED', 'Sampled'), ('COMPLETED', 'Completed')], default='Pending', max_length=20)),
                ('status_datetime', models.DateTimeField(blank=True, null=True)),
                ('requisition_note', models.TextField(blank=True, null=True)),
                ('is_urgent', models.BooleanField()),
                ('lab_cd', models.CharField(blank=True, max_length=10, null=True)),
                ('lab_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('specimen_cd', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'lab_orders',
            },
        ),
        migrations.CreateModel(
            name='MedicalNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField()),
                ('category', models.CharField(blank=True, max_length=50)),
                ('summary', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('url', models.URLField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='이미지 URL')),
            ],
            options={
                'db_table': 'medical_newsletter',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('W', 'Woman')], max_length=1)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('resident_reg_no', models.CharField(max_length=20)),
                ('mail_confirm', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('address', models.CharField(max_length=500)),
                ('provider', models.CharField(choices=[('kakao', 'Kakao'), ('naver', 'Naver'), ('local', 'Local')], default='local', max_length=10)),
                ('provider_id', models.CharField(blank=True, max_length=200, null=True)),
                ('provider_email', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('NURSE', 'Nurse'), ('DOCTOR', 'Doctor'), ('PATIENT', 'Patient'), ('USER', 'User')], max_length=10)),
                ('withdrawal', models.CharField(choices=[('0', 'Active'), ('1', 'Withdrawn')], default='0', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='AiReview',
            fields=[
                ('rev_id', models.AutoField(primary_key=True, serialize=False)),
                ('summary', models.TextField()),
                ('positive_ratio', models.FloatField(blank=True, null=True)),
                ('negative_ratio', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('er', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carebridge_db.erinfo')),
            ],
            options={
                'db_table': 'ai_review',
            },
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('license_no', models.CharField(max_length=50)),
                ('verified', models.BooleanField()),
                ('memo', models.TextField(blank=True, null=True)),
                ('profil_url', models.CharField(blank=True, max_length=255, null=True)),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carebridge_db.department')),
                ('hos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carebridge_db.hospital')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carebridge_db.users')),
            ],
            options={
                'db_table': 'doctors',
            },
        ),
        migrations.CreateModel(
            name='InfectiousStat',
            fields=[
                ('infectious_id', models.AutoField(primary_key=True, serialize=False)),
                ('disease_name', models.CharField(max_length=100)),
                ('stat_date', models.DateField()),
                ('dim_type', models.CharField(choices=[('GENDER', 'Gender'), ('AGE', 'Age'), ('REGION', 'Region')], max_length=10)),
                ('dim_code', models.CharField(max_length=20)),
                ('dim_label', models.CharField(max_length=50)),
                ('result_val', models.IntegerField()),
                ('ptnt_val', models.IntegerField(blank=True, null=True)),
                ('dbtptnt_val', models.IntegerField(blank=True, null=True)),
                ('holder_val', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('disease_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carebridge_db.dimdisease')),
            ],
            options={
                'db_table': 'infectious_stat',
            },
        ),
        migrations.CreateModel(
            name='LabUpload',
            fields=[
                ('lab_upload_id', models.AutoField(primary_key=True, serialize=False)),
                ('uploadedFile', models.FileField(upload_to='lab/')),
                ('original_name', models.CharField(max_length=255)),
                ('datetimeOfUpload', models.DateTimeField(auto_now_add=True)),
                ('lab_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carebridge_db.laborders')),
            ],
            options={
                'db_table': 'lab_upload',
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('medical_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('record_type', models.CharField(max_length=50)),
                ('ptnt_div_cd', models.CharField(choices=[('I', 'Inpatient'), ('O', 'Outpatient'), ('E', 'Emergency')], max_length=1)),
                ('record_datetime', models.DateTimeField()),
                ('record_content', models.TextField(blank=True, null=True)),
                ('subjective', models.TextField(blank=True, null=True)),
                ('objective', models.TextField(blank=True, null=True)),
                ('assessment', models.TextField(blank=True, null=True)),
                ('plan', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carebridge_db.doctors')),
                ('hos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carebridge_db.hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carebridge_db.users')),
            ],
            options={
                'db_table': 'medical_record',
            },
        ),
        migrations.AddField(
            model_name='laborders',
            name='medical_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carebridge_db.medicalrecord'),
        ),
        migrations.CreateModel(
            name='MedicineOrders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_datetime', models.DateTimeField(auto_now_add=True)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('stop_datetime', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('medical_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carebridge_db.medicalrecord')),
            ],
            options={
                'db_table': 'medicine_orders',
            },
        ),
        migrations.CreateModel(
            name='MedicineData',
            fields=[
                ('md_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_code', models.CharField(max_length=50)),
                ('order_name', models.CharField(max_length=50)),
                ('dose', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carebridge_db.medicineorders')),
            ],
            options={
                'db_table': 'medicine_data',
            },
        ),
        migrations.CreateModel(
            name='RawReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_text', models.TextField()),
                ('review_time', models.DateTimeField(blank=True, null=True)),
                ('unique_hash', models.CharField(max_length=255, unique=True)),
                ('er', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_reviews', to='carebridge_db.erinfo')),
            ],
            options={
                'db_table': 'raw_review',
            },
        ),
        migrations.CreateModel(
            name='TimeSlots',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(blank=True, choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10, null=True)),
                ('capacity', models.IntegerField(blank=True, default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carebridge_db.doctors')),
            ],
            options={
                'db_table': 'time_slots',
            },
        ),
        migrations.CreateModel(
            name='TreatmentProcedures',
            fields=[
                ('treatment_id', models.AutoField(primary_key=True, serialize=False)),
                ('procedure_code', models.CharField(blank=True, max_length=50, null=True)),
                ('procedure_name', models.CharField(blank=True, max_length=255, null=True)),
                ('execution_datetime', models.DateTimeField(blank=True, null=True)),
                ('completion_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='Pending', max_length=20)),
                ('treatment_site', models.CharField(blank=True, max_length=100, null=True)),
                ('result_notes', models.TextField(blank=True, null=True)),
                ('medical_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carebridge_db.medicalrecord')),
            ],
            options={
                'db_table': 'treatment_procedures',
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('fav_id', models.AutoField(primary_key=True, serialize=False)),
                ('memo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('er', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carebridge_db.erinfo')),
                ('hos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carebridge_db.hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carebridge_db.users')),
            ],
            options={
                'db_table': 'user_favorite',
            },
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('reserved_at', models.DateTimeField()),
                ('reserved_end', models.DateTimeField()),
                ('slot_type', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carebridge_db.timeslots')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carebridge_db.users')),
            ],
            options={
                'db_table': 'reservations',
            },
        ),
        migrations.CreateModel(
            name='Qna',
            fields=[
                ('qna_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('reply', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('privacy', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carebridge_db.users')),
            ],
            options={
                'db_table': 'qna',
            },
        ),
        migrations.CreateModel(
            name='ErMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('message_time', models.DateTimeField(blank=True, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carebridge_db.erinfo')),
            ],
            options={
                'db_table': 'er_message',
                'unique_together': {('hospital', 'message_time')},
            },
        ),
        migrations.CreateModel(
            name='ErStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hvdate', models.DateTimeField(null=True)),
                ('er_general_available', models.IntegerField(null=True)),
                ('er_general_total', models.IntegerField(null=True)),
                ('er_child_available', models.IntegerField(null=True)),
                ('er_child_total', models.IntegerField(null=True)),
                ('birth_available', models.IntegerField(null=True)),
                ('birth_total', models.IntegerField(null=True)),
                ('negative_pressure_available', models.IntegerField(null=True)),
                ('negative_pressure_total', models.IntegerField(null=True)),
                ('isolation_general_available', models.IntegerField(null=True)),
                ('isolation_general_total', models.IntegerField(null=True)),
                ('isolation_cohort_available', models.IntegerField(null=True)),
                ('isolation_cohort_total', models.IntegerField(null=True)),
                ('has_ct', models.BooleanField(null=True)),
                ('has_mri', models.BooleanField(null=True)),
                ('has_angio', models.BooleanField(blank=True, null=True)),
                ('has_ventilator', models.BooleanField(null=True)),
                ('er', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='carebridge_db.erinfo')),
            ],
            options={
                'db_table': 'er_status',
                'unique_together': {('er', 'hvdate')},
            },
        ),
        migrations.CreateModel(
            name='ErStatusStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hvdate', models.DateTimeField(null=True)),
                ('hvec', models.IntegerField(null=True)),
                ('hvs01', models.IntegerField(null=True)),
                ('hv28', models.IntegerField(null=True)),
                ('hvs02', models.IntegerField(null=True)),
                ('hv42', models.CharField(max_length=10, null=True)),
                ('hvs26', models.IntegerField(null=True)),
                ('hv29', models.IntegerField(null=True)),
                ('hvs03', models.IntegerField(null=True)),
                ('hv30', models.IntegerField(null=True)),
                ('hvs04', models.IntegerField(null=True)),
                ('hv27', models.IntegerField(null=True)),
                ('hvs59', models.IntegerField(null=True)),
                ('hvctayn', models.CharField(max_length=10, null=True)),
                ('hvmriayn', models.CharField(max_length=10, null=True)),
                ('hvangioayn', models.CharField(max_length=10, null=True)),
                ('hvventiayn', models.CharField(max_length=10, null=True)),
                ('hospital', models.ForeignKey(db_column='hpid', on_delete=django.db.models.deletion.CASCADE, to='carebridge_db.erinfo', to_field='hpid')),
            ],
            options={
                'db_table': 'er_status_staging',
                'unique_together': {('hospital', 'hvdate')},
            },
        ),
    ]
