# Generated by Django 5.2.8 on 2025-12-17
# NOTE: DB schema changes are not allowed in this project.
# This migration is intentionally left as a no-op to preserve migration graph integrity.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carebridge_db", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
