# Generated by Django 5.2.8 on 2025-12-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carebridge_db', '0002_medicalrecordreservationmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='sggu',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
