"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import environ
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 로그인 후/로그아웃 후 이동할 URL
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# django-environ 초기화
env = environ.Env(
    DEBUG=(bool, False),
)
env.read_env(os.path.join(BASE_DIR, '.env'))

DEBUG = env('DEBUG')
SECRET_KEY = env('SECRET_KEY', default='django-insecure-coh6tb%m)as!^$=#@(aljpv_7fbih0)x0w-*(b7-mx(8iie*9u')

# 카카오 관련 설정
KAKAO_REST_API_KEY = env('KAKAO_REST_API_KEY', default='')
KAKAO_REDIRECT_URI = env(
    'KAKAO_REDIRECT_URI',
    default=''  # 비어 있으면 나중에 build_absolute_uri로 대체
)
KAKAO_MAP_JS_KEY = os.getenv("KAKAO_REST_API_KEY")

ALLOWED_HOSTS = [
    "52.79.116.240",
    "localhost",
    "127.0.0.1",
    "dn-carebridge.com",
    "www.dn-carebridge.com",
]
CSRF_TRUSTED_ORIGINS = [
    "https://dn-carebridge.com",
    "https://www.dn-carebridge.com",
]

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.accounts',
    'apps.hospitals',
    'apps.reservations',
    'apps.emr',
    'apps.admin_panel',
    'apps.core',
    'apps.newsletter',
    'apps.db.apps.DbConfig',
    'apps.emergency',
    'apps.social_auth',
    'apps.chatbot',
    'apps.mypage',
    'apps.qna',
    'channels'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'apps.emergency.context_processors.kakao_keys',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://doc`s.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv("DB_NAME"),         
        'USER': os.getenv("DB_USER"),     
        'PASSWORD': os.getenv("DB_PASSWORD"),         
        'HOST': os.getenv("DB_HOST"),
        'PORT': os.getenv("DB_PORT"),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        },
    }
}




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ASGI 애플리케이션 지정
ASGI_APPLICATION = 'config.asgi.application'

# [핵심 변경] 채널 레이어 설정 (Redis 사용)
CHANNEL_LAYERS = {
    "default": {
        # Redis를 백엔드로 사용하겠다고 명시
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)], # 1단계에서 띄운 Redis 서버 주소와 포트
            # 실제 배포시에는 AWS ElastiCache 등의 주소를 넣게 됩니다.
        },
    },
}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'
TIME_ZONE = 'Asia/Seoul'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
    BASE_DIR / 'apps/emergency/static',
    BASE_DIR / 'apps/emr/static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LAST_LOGIN_FIELD = None


OPENAPI_SERVICE_KEY = os.getenv("OPENAPI_SERVICE_KEY")

from dotenv import load_dotenv
import urllib.parse

load_dotenv()

RAW_API_KEY = os.getenv("OPENAPI_SERVICE_KEY")
OPENAPI_SERVICE_KEY = urllib.parse.quote(RAW_API_KEY, safe='')

GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")  # 환경변수에서 읽기
GOOGLE_API_KEY = os.getenv("GOOGLE_MAP_API_KEY", "")

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
